# 前のレイヤー（realsense, cyclone_ddsなど）のイメージをベースにする
ARG BASE_IMAGE
FROM ${BASE_IMAGE}

# root権限でパッケージのインストールや設定を行う
USER root

# ROSの環境を読み込めるようにSHELLを設定
SHELL ["/bin/bash", "-c"]

# ワークスペースのパスを変数として定義
ARG ISAAC_ROS_WS=/workspaces/isaac_ros-dev

# -----------------------------------------------------
# APTパッケージとrosdep依存関係のインストール
# -----------------------------------------------------
RUN source /opt/ros/humble/setup.bash && \
    apt-get update && \
    apt-get install -y \
        ros-humble-isaac-ros-examples \
        ros-humble-isaac-ros-realsense \
    && rm -rf /var/lib/apt/lists/* && \
    rosdep update && \
    rosdep install --from-paths ${ISAAC_ROS_WS}/src/isaac_ros_visual_slam/isaac_ros_visual_slam --ignore-src -r -y

# -----------------------------------------------------
# Colconビルドの実行
# -----------------------------------------------------
RUN source /opt/ros/humble/setup.bash && \
    cd ${ISAAC_ROS_WS} && \
    colcon build --symlink-install --packages-up-to isaac_ros_visual_slam

# -----------------------------------------------------
# ワークスペースの自動セットアップ
# -----------------------------------------------------
# コンテナ起動時に自動でsourceされるように.bashrcに追記
RUN echo "source ${ISAAC_ROS_WS}/install/setup.bash" >> /home/admin/.bashrc

# ユーザーをadminに戻す
USER admin