# ISAAC ROSの基本イメージをベースにする
ARG BASE_IMAGE
FROM ${BASE_IMAGE}

# root権限が必要なシステム設定を行う
USER root

# 1. aptパッケージのインストール
RUN apt-get update && \
    apt-get install -y \
    tmux \
    iproute2 \
    terminator \
    vim \
    htop \
    can-utils && \
    rm -rf /var/lib/apt/lists/*

# 2. CycloneDDSの設定ファイルと環境変数を追加
COPY middleware_profiles/cyclonedds.xml /etc/cyclonedds.xml
# 環境変数を設定
ENV RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
ENV CYCLONEDDS_URI=file:///etc/cyclonedds.xml

# adminユーザーが存在することを保証する
ARG HOST_USER_UID=1000
ARG HOST_USER_GID=1000
RUN groupadd -f -g $HOST_USER_GID admin && \
    useradd -o -u $HOST_USER_UID -g $HOST_USER_GID -m -s /bin/bash admin && \
    echo "admin ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers.d/admin-nopasswd