# 前のレイヤーのイメージをベースにする
ARG BASE_IMAGE
FROM ${BASE_IMAGE}

# root権限でパッケージのインストールを行う
USER root
SHELL ["/bin/bash", "-c"]

# ----------------------------------------------------------------
# aptで必要なISAAC ROSパッケージをすべてインストール
# ----------------------------------------------------------------
RUN apt-get update && \
    apt-get install -y \
        ros-humble-ackermann-msgs \
        ros-humble-isaac-ros-examples \
        ros-humble-isaac-ros-realsense \
        ros-humble-isaac-ros-h264-decoder \
        ros-humble-isaac-ros-launch-utils \
        ros-humble-isaac-ros-test \
        ros-humble-isaac-ros-visual-slam-interfaces \
        ros-humble-gxf-isaac-image-flip \
        ros-humble-gxf-isaac-tensorops \
        ros-humble-isaac-ros-image-proc \
        ros-humble-isaac-ros-nitros-compressed-image-type \
        ros-humble-isaac-ros-tensor-rt \
        ros-humble-isaac-ros-dnn-image-encoder \
        ros-humble-isaac-ros-visual-slam \
        ros-humble-rqt-robot-monitor \
        ros-humble-isaac-ros-jetson-stats \
        ros-humble-rtabmap-ros \
    && \
    # イメージサイズを小さく保つため、aptキャッシュを削除
    rm -rf /var/lib/apt/lists/*


# ----------------------------------------------------------------
# aptで必要なパッケージをすべてインストール
# ---------------------------------------------------------------- 
RUN apt-get update && \
    apt-get install -y \
        bluez \
        joystick \
        git \
    && \
    # イメージサイズを小さく保ため、aptキャッシュを削除
    rm -rf /var/lib/apt/lists/*


# ----------------------------------------------------------------
# Jetracerライブラリをソースからインストール 
# ----------------------------------------------------------------
RUN set -x && \
    # 一時的な作業ディレクトリに移動
    cd /tmp && \
    # ソースコードをクローン
    git clone https://github.com/NVIDIA-AI-IOT/jetracer.git && \
    # クローンしたディレクトリに移動
    cd jetracer && \
    # Jetracerライブラリをインストール (root権限のためsudoは不要)
    python3 setup.py install && \
    # 依存するpipパッケージをインストール
    pip3 install traitlets questionary jetson-gpio  && \
    # イメージサイズ削減のため、クリーンアップ
    cd / && rm -rf /tmp/*


COPY scripts/entrypoint_addition[s]/*.sh /usr/local/bin/scripts/entrypoint_additions/
RUN chmod +x /usr/local/bin/scripts/entrypoint_additions/*.sh || true

COPY scripts/my_additions/*.sh /my_scripts/

# デフォルトの作業ディレクトリを設定
WORKDIR /workspaces