# ISAAC ROSの基本イメージをベースにする
ARG BASE_IMAGE
FROM ${BASE_IMAGE}

# root権限が必要なシステム設定を行う
USER root

# 1. Autoware向け通信・マルチキャスト設定
RUN \
    tee /etc/systemd/system/multicast-lo.service > /dev/null <<EOF && \
[Unit]
Description=Enable Multicast on Loopback
[Service]
Type=oneshot
ExecStart=/bin/sh -c "/usr/sbin/ip link set lo multicast on"
RemainAfterExit=true
[Install]
WantedBy=multi-user.target
EOF
    \
    tee /etc/sysctl.d/10-cyclone-max.conf > /dev/null <<EOF && \
net.core.rmem_max=2147483647
net.ipv4.ipfrag_time=3
net.ipv4.ipfrag_high_thresh=134217728
EOF
    \
    systemctl enable multicast-lo.service && \
    sysctl --system

# 2. aptパッケージのインストール
RUN apt-get update && \
    apt-get install -y \
    tmux \
    terminator \
    vim \
    htop \
    can-utils && \
    rm -rf /var/lib/apt/lists/*

# 3. CycloneDDSの設定ファイルと環境変数を追加
COPY ../docker/middleware_profiles/cyclonedds.xml /etc/cyclonedds.xml
# 環境変数を設定
ENV RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
ENV CYCLONEDDS_URI=file:///etc/cyclonedds.xml

# デフォルトの非rootユーザーに戻す
USER admin