# 前のレイヤーのイメージをベースにする
ARG BASE_IMAGE
FROM ${BASE_IMAGE}

# root権限でパッケージのインストールを行う
USER root
SHELL ["/bin/bash", "-c"]

# ----------------------------------------------------------------
# aptで必要なROSパッケージをすべてインストール
# ----------------------------------------------------------------
RUN apt-get update && \
    apt-get install -y \
        ros-humble-ackermann-msgs \
        ros-humble-isaac-ros-examples \
        ros-humble-isaac-ros-realsense \
        ros-humble-isaac-ros-h264-decoder \
        ros-humble-isaac-ros-launch-utils \
        ros-humble-isaac-ros-test \
        ros-humble-isaac-ros-visual-slam-interfaces \
        ros-humble-gxf-isaac-image-flip \
        ros-humble-gxf-isaac-tensorops \
        ros-humble-isaac-ros-image-proc \
        ros-humble-isaac-ros-nitros-compressed-image-type \
        ros-humble-isaac-ros-tensor-rt \
        ros-humble-isaac-ros-dnn-image-encoder \
        ros-humble-isaac-ros-visual-slam \
        ros-humble-rtabmap-ros \
    && \
    # イメージサイズを小さく保つため、aptキャッシュを削除
    rm -rf /var/lib/apt/lists/*

# デフォルトの作業ディレクトリを設定
WORKDIR /workspaces